### PR TITLE
En us

### PR DESCRIPTION
**Pull request by archae0pteryx**
I have been going back and forth on the best way to do this. How should I proceed? Create a new file for the translations, or, is it ok to use the en-us branch, replacing the "original" chinese text with google-translate as I go. I want to do a bulk translate and then read through as I have time. What do you think is the best approach?

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
I think Just do a google translate, and gradually refine stuff.

**Comment by daogangtang** [comment]
merge to master?

**Comment by archae0pteryx** [comment]
I think for now what I'll do is commit to en-us, replacing the Chinese version with Google, then refactor. I thought that it might be tough to keep the English version current, then I realized I'd be able to just diff my master w yours. Make sense?

**Comment by MarisaKirisame** [comment]
Yep

**Pull request closed without merging**
